#%RAML 1.0 DataType 
type: object
properties:
  email:
    type: string
    example: aslam.bari@gmail.com
    required: true
  phone:
    type: string
    example: '9251425422'
    required: false
  lastname:
    type: string
    example: Bari
    required: false
